"""Collect experiments/runs/*.json into experiments/RESULTS.md, one row per run.

  python tools/summarize_runs.py

Rows are sorted by ret_sim of the final evaluation (best captioning checkpoint). The
best value of each metric column is marked with *. Lessons and plans live in
experiments/NOTES.md, which is written by hand.
"""
import glob
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RUNS = os.path.join(ROOT, 'experiments', 'runs')
OUT = os.path.join(ROOT, 'experiments', 'RESULTS.md')

# (header, key in final_eval or best, format, higher is better)
COLS = [('R@0.5', 'R@0.5', '%.2f'), ('R@0.7', 'R@0.7', '%.2f'), ('mIoU', 'mIoU', '%.2f'),
        ('ret_sim', 'ret_sim', '%.3f'), ('top1', 'ret_sim[top1]', '%.3f'), ('CIDEr', 'CIDEr', '%.1f'),
        ('METEOR', 'METEOR', '%.2f'), ('oracle', 'ret_sim[oracle]', '%.3f'),
        ('best seg R@0.5', None, '%.2f')]


def load():
    rows = []
    for f in sorted(glob.glob(os.path.join(RUNS, '*.json'))):
        d = json.load(open(f))
        fe = d.get('final_eval') or {}
        r = {h: fe.get(k) for h, k, _ in COLS if k}
        r['best seg R@0.5'] = (d.get('best') or {}).get('R@0.5', {}).get('value')
        r.update(run=d['run'], host=d.get('host', '?'), commit=(d.get('git') or {}).get('commit', '?'),
                 dirty=(d.get('git') or {}).get('dirty'), overrides=' '.join(d.get('overrides') or []) or '-',
                 note=d.get('note') or '', finished=d.get('finished') or 'running',
                 teacher='yes' if (d.get('config') or {}).get('dataset', {}).get('omni_emb_file') else 'no')
        rows.append(r)
    return rows


def main():
    rows = load()
    rows.sort(key=lambda r: -(r['ret_sim'] or 0))
    best = {h: max((r[h] for r in rows if r[h] is not None), default=None) for h, _, _ in COLS}
    lines = ['# Experiment results', '',
             'Generated by `tools/summarize_runs.py` from `experiments/runs/*.json`. Do not edit by hand.',
             'Metrics are from the full evaluation of each run\'s best-CIDEr checkpoint; `best seg R@0.5`',
             'is the best R@0.5 seen during training. `*` marks the best value per column.',
             'Run-to-run noise (seed only): R@0.5 about 2, CIDEr about 5, ret_sim about 0.003.', '',
             '| run | host | commit | teacher | overrides | ' + ' | '.join(h for h, _, _ in COLS) + ' | note |',
             '|' + '---|' * (6 + len(COLS))]
    for r in rows:
        cells = []
        for h, _, fmt in COLS:
            v = r[h]
            cells.append('-' if v is None else (fmt % v) + ('*' if v == best[h] else ''))
        commit = r['commit'] + ('+dirty' if r['dirty'] else '')
        lines.append('| %s | %s | %s | %s | `%s` | %s | %s |' % (
            r['run'], r['host'], commit, r['teacher'], r['overrides'], ' | '.join(cells), r['note']))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, 'w').write('\n'.join(lines) + '\n')
    print('\n'.join(lines))


if __name__ == '__main__':
    main()
